export const NOTIFICATION_EVENTS = {
  USER_APPROVED: "USER_APPROVED",

  USER_REJECTED: "USER_REJECTED",

  JOB_POSTED: "JOB_POSTED",

  JOB_PUBLISHED: "JOB_PUBLISHED",

  APPLICATION_CREATED: "APPLICATION_CREATED",

  APPLICATION_VERIFIED: "APPLICATION_VERIFIED",

  APPLICATION_REJECTED: "APPLICATION_REJECTED",

  APPLICATION_UPDATE_REQUESTED: "APPLICATION_UPDATE_REQUESTED",

  CLIENT_SUBMISSION_CREATED: "CLIENT_SUBMISSION_CREATED",

  CLIENT_CANDIDATE_SHORTLISTED: "CLIENT_CANDIDATE_SHORTLISTED",

  CLIENT_CANDIDATE_REJECTED: "CLIENT_CANDIDATE_REJECTED",

  MOCK_SCHEDULED: "MOCK_SCHEDULED",

  MOCK_RESCHEDULED: "MOCK_RESCHEDULED",

  MOCK_CANCELLED: "MOCK_CANCELLED",

  MOCK_REMINDER: "MOCK_REMINDER",

  MOCK_COMPLETED: "MOCK_COMPLETED",

  CLIENT_INTERVIEW_SCHEDULED: "CLIENT_INTERVIEW_SCHEDULED",

  CLIENT_INTERVIEW_RESCHEDULED: "CLIENT_INTERVIEW_RESCHEDULED",

  CLIENT_INTERVIEW_CANCELLED: "CLIENT_INTERVIEW_CANCELLED",

  CLIENT_INTERVIEW_REMINDER: "CLIENT_INTERVIEW_REMINDER",

  CLIENT_INTERVIEW_COMPLETED: "CLIENT_INTERVIEW_COMPLETED",

  INTERVIEW_FEEDBACK_SUBMITTED: "INTERVIEW_FEEDBACK_SUBMITTED",

  FEEDBACK_DUE: "FEEDBACK_DUE",

  FEEDBACK_OVERDUE: "FEEDBACK_OVERDUE",

  FEEDBACK_ESCALATION: "FEEDBACK_ESCALATION",

  CANDIDATE_SELECTED: "CANDIDATE_SELECTED",

  CANDIDATE_REJECTED_INTERVIEW: "CANDIDATE_REJECTED_INTERVIEW",

  CANDIDATE_ON_HOLD: "CANDIDATE_ON_HOLD",

  OFFER_RECEIVED: "OFFER_RECEIVED",

  OFFER_EXPIRING: "OFFER_EXPIRING",

  OFFER_ACCEPTED: "OFFER_ACCEPTED",

  OFFER_DECLINED: "OFFER_DECLINED",

  CANDIDATE_PLACED: "CANDIDATE_PLACED",

  CANDIDATE_JOINED: "CANDIDATE_JOINED",

  PLACEMENT_CLOSED: "PLACEMENT_CLOSED",

  STUDENT_CV_REMINDER: "STUDENT_CV_REMINDER",
} as const;

export type NotificationEvent =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];
