// Generated from the migrated PostgreSQL catalogs by scripts/generate-database-types.mjs.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database={public:{Tables:{"ai_generation_runs":{Row:{"id": string;
"entity_type": string;
"entity_id": string;
"operation": string;
"provider": string;
"model": string;
"prompt_version": string;
"status": string;
"requested_by": string;
"input_snapshot": Json;
"output_snapshot": Json | null;
"response_id": string | null;
"input_tokens": number | null;
"output_tokens": number | null;
"total_tokens": number | null;
"error_message": string | null;
"started_at": string;
"completed_at": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"entity_type": string;
"entity_id": string;
"operation": string;
"provider": string;
"model": string;
"prompt_version": string;
"status"?: string;
"requested_by": string;
"input_snapshot"?: Json;
"output_snapshot"?: Json | null;
"response_id"?: string | null;
"input_tokens"?: number | null;
"output_tokens"?: number | null;
"total_tokens"?: number | null;
"error_message"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"entity_type"?: string;
"entity_id"?: string;
"operation"?: string;
"provider"?: string;
"model"?: string;
"prompt_version"?: string;
"status"?: string;
"requested_by"?: string;
"input_snapshot"?: Json;
"output_snapshot"?: Json | null;
"response_id"?: string | null;
"input_tokens"?: number | null;
"output_tokens"?: number | null;
"total_tokens"?: number | null;
"error_message"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"ai_generation_runs_requested_by_fkey";columns:["requested_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"application_requirement_matches":{Row:{"id": number;
"application_score_id": string;
"requirement_type": string;
"requirement_name": string;
"normalized_requirement": string;
"matched": boolean;
"matched_cv_term": string | null;
"match_method": string;
"confidence": number;
"evidence": string | null;
"created_at": string};Insert:{"id"?: never;
"application_score_id": string;
"requirement_type": string;
"requirement_name": string;
"normalized_requirement": string;
"matched": boolean;
"matched_cv_term"?: string | null;
"match_method": string;
"confidence": number;
"evidence"?: string | null;
"created_at"?: string};Update:{"id"?: never;
"application_score_id"?: string;
"requirement_type"?: string;
"requirement_name"?: string;
"normalized_requirement"?: string;
"matched"?: boolean;
"matched_cv_term"?: string | null;
"match_method"?: string;
"confidence"?: number;
"evidence"?: string | null;
"created_at"?: string};Relationships:[{foreignKeyName:"application_requirement_matches_application_score_id_fkey";columns:["application_score_id"];isOneToOne:false;referencedRelation:"application_scores";referencedColumns:["id"]}]};
"application_scores":{Row:{"id": string;
"application_id": string;
"parsed_cv_profile_id": string;
"checklist_id": string;
"scoring_engine_version": string;
"match_score": number;
"must_have_score": number;
"good_to_have_score": number;
"tools_score": number;
"must_have_coverage": number;
"good_to_have_coverage": number;
"tools_coverage": number;
"ats_score": number;
"ats_contact_score": number;
"ats_skills_score": number;
"ats_experience_score": number;
"ats_formatting_score": number;
"ats_length_score": number;
"breakdown": Json;
"created_at": string};Insert:{"id"?: string;
"application_id": string;
"parsed_cv_profile_id": string;
"checklist_id": string;
"scoring_engine_version": string;
"match_score": number;
"must_have_score": number;
"good_to_have_score": number;
"tools_score": number;
"must_have_coverage": number;
"good_to_have_coverage": number;
"tools_coverage": number;
"ats_score": number;
"ats_contact_score": number;
"ats_skills_score": number;
"ats_experience_score": number;
"ats_formatting_score": number;
"ats_length_score": number;
"breakdown"?: Json;
"created_at"?: string};Update:{"id"?: string;
"application_id"?: string;
"parsed_cv_profile_id"?: string;
"checklist_id"?: string;
"scoring_engine_version"?: string;
"match_score"?: number;
"must_have_score"?: number;
"good_to_have_score"?: number;
"tools_score"?: number;
"must_have_coverage"?: number;
"good_to_have_coverage"?: number;
"tools_coverage"?: number;
"ats_score"?: number;
"ats_contact_score"?: number;
"ats_skills_score"?: number;
"ats_experience_score"?: number;
"ats_formatting_score"?: number;
"ats_length_score"?: number;
"breakdown"?: Json;
"created_at"?: string};Relationships:[{foreignKeyName:"application_scores_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"application_scores_checklist_id_fkey";columns:["checklist_id"];isOneToOne:false;referencedRelation:"job_checklists";referencedColumns:["id"]},{foreignKeyName:"application_scores_parsed_cv_profile_id_fkey";columns:["parsed_cv_profile_id"];isOneToOne:false;referencedRelation:"parsed_cv_profiles";referencedColumns:["id"]}]};
"application_scoring_runs":{Row:{"id": string;
"application_id": string;
"status": string;
"attempt": number;
"started_by": string | null;
"started_at": string;
"completed_at": string | null;
"error_message": string | null;
"application_score_id": string | null};Insert:{"id"?: string;
"application_id": string;
"status": string;
"attempt"?: number;
"started_by"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"error_message"?: string | null;
"application_score_id"?: string | null};Update:{"id"?: string;
"application_id"?: string;
"status"?: string;
"attempt"?: number;
"started_by"?: string | null;
"started_at"?: string;
"completed_at"?: string | null;
"error_message"?: string | null;
"application_score_id"?: string | null};Relationships:[{foreignKeyName:"application_scoring_runs_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"application_scoring_runs_application_score_id_fkey";columns:["application_score_id"];isOneToOne:false;referencedRelation:"application_scores";referencedColumns:["id"]},{foreignKeyName:"application_scoring_runs_started_by_fkey";columns:["started_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"application_state_transitions":{Row:{"from_status": string;
"to_status": string;
"description": string | null};Insert:{"from_status": string;
"to_status": string;
"description"?: string | null};Update:{"from_status"?: string;
"to_status"?: string;
"description"?: string | null};Relationships:[]};
"application_status_history":{Row:{"id": number;
"application_id": string;
"old_status": string | null;
"new_status": string;
"reason": string | null;
"changed_by": string | null;
"metadata": Json;
"changed_at": string};Insert:{"id"?: never;
"application_id": string;
"old_status"?: string | null;
"new_status": string;
"reason"?: string | null;
"changed_by"?: string | null;
"metadata"?: Json;
"changed_at"?: string};Update:{"id"?: never;
"application_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"reason"?: string | null;
"changed_by"?: string | null;
"metadata"?: Json;
"changed_at"?: string};Relationships:[{foreignKeyName:"application_status_history_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"application_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"application_verifications":{Row:{"id": string;
"application_id": string;
"assignment_id": string | null;
"verification_status": string;
"original_match_score": number | null;
"final_match_score": number | null;
"original_ats_score": number | null;
"final_ats_score": number | null;
"must_have_verified": boolean;
"cv_verified": boolean;
"experience_verified": boolean;
"domain_verified": boolean;
"notes": string | null;
"rejection_reason": string | null;
"update_request": string | null;
"verified_by": string;
"verified_at": string;
"created_at": string};Insert:{"id"?: string;
"application_id": string;
"assignment_id"?: string | null;
"verification_status": string;
"original_match_score"?: number | null;
"final_match_score"?: number | null;
"original_ats_score"?: number | null;
"final_ats_score"?: number | null;
"must_have_verified"?: boolean;
"cv_verified"?: boolean;
"experience_verified"?: boolean;
"domain_verified"?: boolean;
"notes"?: string | null;
"rejection_reason"?: string | null;
"update_request"?: string | null;
"verified_by": string;
"verified_at"?: string;
"created_at"?: string};Update:{"id"?: string;
"application_id"?: string;
"assignment_id"?: string | null;
"verification_status"?: string;
"original_match_score"?: number | null;
"final_match_score"?: number | null;
"original_ats_score"?: number | null;
"final_ats_score"?: number | null;
"must_have_verified"?: boolean;
"cv_verified"?: boolean;
"experience_verified"?: boolean;
"domain_verified"?: boolean;
"notes"?: string | null;
"rejection_reason"?: string | null;
"update_request"?: string | null;
"verified_by"?: string;
"verified_at"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"application_verifications_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"application_verifications_assignment_id_fkey";columns:["assignment_id"];isOneToOne:false;referencedRelation:"verification_assignments";referencedColumns:["id"]},{foreignKeyName:"application_verifications_verified_by_fkey";columns:["verified_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"applications":{Row:{"id": string;
"job_id": string;
"student_id": string;
"cv_id": string;
"checklist_id": string;
"status": string;
"score_status": string;
"match_score": number | null;
"ats_score": number | null;
"scoring_error": string | null;
"applied_at": string;
"created_at": string;
"updated_at": string;
"verified_match_score": number | null;
"verified_ats_score": number | null;
"verification_notes": string | null;
"rejection_reason": string | null;
"update_request": string | null;
"verified_by": string | null;
"verified_at": string | null;
"verification_due_at": string | null;
"submitted_to_client_at": string | null;
"submitted_by": string | null;
"shortlisted_at": string | null;
"selected_at": string | null;
"offer_received_at": string | null;
"offer_accepted_at": string | null;
"placed_at": string | null;
"selected_for_offer_at": string | null;
"submitted_at": string | null;
"withdrawn_at": string | null;
"withdrawal_reason": string | null;
"verification_pending_at": string | null};Insert:{"id"?: string;
"job_id": string;
"student_id": string;
"cv_id": string;
"checklist_id": string;
"status"?: string;
"score_status"?: string;
"match_score"?: number | null;
"ats_score"?: number | null;
"scoring_error"?: string | null;
"applied_at"?: string;
"created_at"?: string;
"updated_at"?: string;
"verified_match_score"?: number | null;
"verified_ats_score"?: number | null;
"verification_notes"?: string | null;
"rejection_reason"?: string | null;
"update_request"?: string | null;
"verified_by"?: string | null;
"verified_at"?: string | null;
"verification_due_at"?: string | null;
"submitted_to_client_at"?: string | null;
"submitted_by"?: string | null;
"shortlisted_at"?: string | null;
"selected_at"?: string | null;
"offer_received_at"?: string | null;
"offer_accepted_at"?: string | null;
"placed_at"?: string | null;
"selected_for_offer_at"?: string | null;
"submitted_at"?: string | null;
"withdrawn_at"?: string | null;
"withdrawal_reason"?: string | null;
"verification_pending_at"?: string | null};Update:{"id"?: string;
"job_id"?: string;
"student_id"?: string;
"cv_id"?: string;
"checklist_id"?: string;
"status"?: string;
"score_status"?: string;
"match_score"?: number | null;
"ats_score"?: number | null;
"scoring_error"?: string | null;
"applied_at"?: string;
"created_at"?: string;
"updated_at"?: string;
"verified_match_score"?: number | null;
"verified_ats_score"?: number | null;
"verification_notes"?: string | null;
"rejection_reason"?: string | null;
"update_request"?: string | null;
"verified_by"?: string | null;
"verified_at"?: string | null;
"verification_due_at"?: string | null;
"submitted_to_client_at"?: string | null;
"submitted_by"?: string | null;
"shortlisted_at"?: string | null;
"selected_at"?: string | null;
"offer_received_at"?: string | null;
"offer_accepted_at"?: string | null;
"placed_at"?: string | null;
"selected_for_offer_at"?: string | null;
"submitted_at"?: string | null;
"withdrawn_at"?: string | null;
"withdrawal_reason"?: string | null;
"verification_pending_at"?: string | null};Relationships:[{foreignKeyName:"applications_checklist_id_fkey";columns:["checklist_id"];isOneToOne:false;referencedRelation:"job_checklists";referencedColumns:["id"]},{foreignKeyName:"applications_cv_id_fkey";columns:["cv_id"];isOneToOne:false;referencedRelation:"student_cvs";referencedColumns:["id"]},{foreignKeyName:"applications_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"applications_student_id_fkey";columns:["student_id"];isOneToOne:false;referencedRelation:"student_profiles";referencedColumns:["id"]},{foreignKeyName:"applications_submitted_by_fkey";columns:["submitted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"applications_verified_by_fkey";columns:["verified_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"audit_logs":{Row:{"id": number;
"actor_id": string | null;
"actor_role": string | null;
"action": string;
"entity_type": string;
"entity_id": string | null;
"old_values": Json | null;
"new_values": Json | null;
"metadata": Json;
"ip_address": string | null;
"user_agent": string | null;
"request_id": string | null;
"created_at": string};Insert:{"id"?: never;
"actor_id"?: string | null;
"actor_role"?: string | null;
"action": string;
"entity_type": string;
"entity_id"?: string | null;
"old_values"?: Json | null;
"new_values"?: Json | null;
"metadata"?: Json;
"ip_address"?: string | null;
"user_agent"?: string | null;
"request_id"?: string | null;
"created_at"?: string};Update:{"id"?: never;
"actor_id"?: string | null;
"actor_role"?: string | null;
"action"?: string;
"entity_type"?: string;
"entity_id"?: string | null;
"old_values"?: Json | null;
"new_values"?: Json | null;
"metadata"?: Json;
"ip_address"?: string | null;
"user_agent"?: string | null;
"request_id"?: string | null;
"created_at"?: string};Relationships:[{foreignKeyName:"audit_logs_actor_id_fkey";columns:["actor_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"client_candidate_decision_history":{Row:{"id": number;
"submission_candidate_id": string;
"old_decision": string | null;
"new_decision": string;
"reason_code": string | null;
"reason": string | null;
"changed_by": string;
"changed_at": string};Insert:{"id"?: never;
"submission_candidate_id": string;
"old_decision"?: string | null;
"new_decision": string;
"reason_code"?: string | null;
"reason"?: string | null;
"changed_by": string;
"changed_at"?: string};Update:{"id"?: never;
"submission_candidate_id"?: string;
"old_decision"?: string | null;
"new_decision"?: string;
"reason_code"?: string | null;
"reason"?: string | null;
"changed_by"?: string;
"changed_at"?: string};Relationships:[{foreignKeyName:"client_candidate_decision_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"client_candidate_decision_history_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]}]};
"client_candidate_decisions":{Row:{"id": string;
"submission_candidate_id": string;
"application_id": string;
"company_id": string;
"decision": string;
"reason_code": string | null;
"reason": string | null;
"decision_version": number;
"is_current": boolean;
"decided_by": string;
"decided_at": string;
"created_at": string};Insert:{"id"?: string;
"submission_candidate_id": string;
"application_id": string;
"company_id": string;
"decision": string;
"reason_code"?: string | null;
"reason"?: string | null;
"decision_version"?: number;
"is_current"?: boolean;
"decided_by": string;
"decided_at"?: string;
"created_at"?: string};Update:{"id"?: string;
"submission_candidate_id"?: string;
"application_id"?: string;
"company_id"?: string;
"decision"?: string;
"reason_code"?: string | null;
"reason"?: string | null;
"decision_version"?: number;
"is_current"?: boolean;
"decided_by"?: string;
"decided_at"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"client_candidate_decisions_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"client_candidate_decisions_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"client_candidate_decisions_decided_by_fkey";columns:["decided_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"client_candidate_decisions_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]}]};
"client_hr_profiles":{Row:{"id": string;
"user_id": string;
"company_id": string;
"employee_code": string | null;
"designation": string | null;
"department": string | null;
"work_email": string | null;
"work_phone": string | null;
"linkedin_url": string | null;
"is_primary_contact": boolean;
"is_active": boolean;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"user_id": string;
"company_id": string;
"employee_code"?: string | null;
"designation"?: string | null;
"department"?: string | null;
"work_email"?: string | null;
"work_phone"?: string | null;
"linkedin_url"?: string | null;
"is_primary_contact"?: boolean;
"is_active"?: boolean;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"user_id"?: string;
"company_id"?: string;
"employee_code"?: string | null;
"designation"?: string | null;
"department"?: string | null;
"work_email"?: string | null;
"work_phone"?: string | null;
"linkedin_url"?: string | null;
"is_primary_contact"?: boolean;
"is_active"?: boolean;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"client_hr_profiles_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"client_hr_profiles_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"companies":{Row:{"id": string;
"name": string;
"legal_name": string | null;
"code": string | null;
"domain": string | null;
"website": string | null;
"industry": string | null;
"size": string | null;
"registration_number": string | null;
"gst_number": string | null;
"linkedin_url": string | null;
"primary_email": string | null;
"primary_phone": string | null;
"address": string | null;
"city": string | null;
"state": string | null;
"country": string | null;
"postal_code": string | null;
"logo": string | null;
"verification_status": string;
"verification_method": string | null;
"verification_notes": string | null;
"verified_at": string | null;
"verified_by": string | null;
"is_active": boolean;
"created_by": string | null;
"created_at": string;
"updated_at": string;
"deleted_at": string | null;
"deleted_by": string | null;
"rejection_reason": string | null;
"address_line_1": string | null;
"address_line_2": string | null;
"notes": string | null};Insert:{"id"?: string;
"name": string;
"legal_name"?: string | null;
"code"?: string | null;
"domain"?: string | null;
"website"?: string | null;
"industry"?: string | null;
"size"?: string | null;
"registration_number"?: string | null;
"gst_number"?: string | null;
"linkedin_url"?: string | null;
"primary_email"?: string | null;
"primary_phone"?: string | null;
"address"?: string | null;
"city"?: string | null;
"state"?: string | null;
"country"?: string | null;
"postal_code"?: string | null;
"logo"?: string | null;
"verification_status"?: string;
"verification_method"?: string | null;
"verification_notes"?: string | null;
"verified_at"?: string | null;
"verified_by"?: string | null;
"is_active"?: boolean;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null;
"rejection_reason"?: string | null;
"address_line_1"?: string | null;
"address_line_2"?: string | null;
"notes"?: string | null};Update:{"id"?: string;
"name"?: string;
"legal_name"?: string | null;
"code"?: string | null;
"domain"?: string | null;
"website"?: string | null;
"industry"?: string | null;
"size"?: string | null;
"registration_number"?: string | null;
"gst_number"?: string | null;
"linkedin_url"?: string | null;
"primary_email"?: string | null;
"primary_phone"?: string | null;
"address"?: string | null;
"city"?: string | null;
"state"?: string | null;
"country"?: string | null;
"postal_code"?: string | null;
"logo"?: string | null;
"verification_status"?: string;
"verification_method"?: string | null;
"verification_notes"?: string | null;
"verified_at"?: string | null;
"verified_by"?: string | null;
"is_active"?: boolean;
"created_by"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null;
"rejection_reason"?: string | null;
"address_line_1"?: string | null;
"address_line_2"?: string | null;
"notes"?: string | null};Relationships:[{foreignKeyName:"companies_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"companies_deleted_by_fkey";columns:["deleted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"companies_verified_by_fkey";columns:["verified_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"company_status_history":{Row:{"id": string;
"company_id": string;
"old_status": string | null;
"new_status": string;
"reason": string | null;
"changed_by": string | null;
"changed_at": string};Insert:{"id"?: string;
"company_id": string;
"old_status"?: string | null;
"new_status": string;
"reason"?: string | null;
"changed_by"?: string | null;
"changed_at"?: string};Update:{"id"?: string;
"company_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"reason"?: string | null;
"changed_by"?: string | null;
"changed_at"?: string};Relationships:[{foreignKeyName:"company_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"company_status_history_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]}]};
"deployment_audit_logs":{Row:{"id": number;
"release_version": string;
"environment": string;
"event": string;
"status": string;
"metadata": Json;
"created_at": string};Insert:{"id"?: never;
"release_version": string;
"environment": string;
"event": string;
"status": string;
"metadata"?: Json;
"created_at"?: string};Update:{"id"?: never;
"release_version"?: string;
"environment"?: string;
"event"?: string;
"status"?: string;
"metadata"?: Json;
"created_at"?: string};Relationships:[]};
"interview_feedback_revisions":{Row:{"id": string;
"feedback_id": string;
"revision_number": number;
"previous_rating": number | null;
"previous_decision": string | null;
"previous_reason_code": string | null;
"previous_comments": string | null;
"new_rating": number | null;
"new_decision": string | null;
"new_reason_code": string | null;
"new_comments": string | null;
"reason": string;
"revised_by": string;
"revised_at": string};Insert:{"id"?: string;
"feedback_id": string;
"revision_number": number;
"previous_rating"?: number | null;
"previous_decision"?: string | null;
"previous_reason_code"?: string | null;
"previous_comments"?: string | null;
"new_rating"?: number | null;
"new_decision"?: string | null;
"new_reason_code"?: string | null;
"new_comments"?: string | null;
"reason": string;
"revised_by": string;
"revised_at"?: string};Update:{"id"?: string;
"feedback_id"?: string;
"revision_number"?: number;
"previous_rating"?: number | null;
"previous_decision"?: string | null;
"previous_reason_code"?: string | null;
"previous_comments"?: string | null;
"new_rating"?: number | null;
"new_decision"?: string | null;
"new_reason_code"?: string | null;
"new_comments"?: string | null;
"reason"?: string;
"revised_by"?: string;
"revised_at"?: string};Relationships:[{foreignKeyName:"interview_feedback_revisions_feedback_id_fkey";columns:["feedback_id"];isOneToOne:false;referencedRelation:"interview_feedbacks";referencedColumns:["id"]},{foreignKeyName:"interview_feedback_revisions_revised_by_fkey";columns:["revised_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"interview_feedbacks":{Row:{"id": string;
"feedback_code": string | null;
"interview_id": string;
"application_id": string;
"submission_candidate_id": string;
"company_id": string;
"rating": number | null;
"decision": string;
"reason_code": string | null;
"comments": string | null;
"client_visible_to_student": boolean;
"feedback_due_at": string | null;
"feedback_status": string;
"submitted_by": string;
"submitted_at": string;
"revised_at": string | null;
"revised_by": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"feedback_code"?: string | null;
"interview_id": string;
"application_id": string;
"submission_candidate_id": string;
"company_id": string;
"rating"?: number | null;
"decision": string;
"reason_code"?: string | null;
"comments"?: string | null;
"client_visible_to_student"?: boolean;
"feedback_due_at"?: string | null;
"feedback_status"?: string;
"submitted_by": string;
"submitted_at"?: string;
"revised_at"?: string | null;
"revised_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"feedback_code"?: string | null;
"interview_id"?: string;
"application_id"?: string;
"submission_candidate_id"?: string;
"company_id"?: string;
"rating"?: number | null;
"decision"?: string;
"reason_code"?: string | null;
"comments"?: string | null;
"client_visible_to_student"?: boolean;
"feedback_due_at"?: string | null;
"feedback_status"?: string;
"submitted_by"?: string;
"submitted_at"?: string;
"revised_at"?: string | null;
"revised_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"interview_feedbacks_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"interview_feedbacks_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"interview_feedbacks_interview_id_fkey";columns:["interview_id"];isOneToOne:false;referencedRelation:"interviews";referencedColumns:["id"]},{foreignKeyName:"interview_feedbacks_revised_by_fkey";columns:["revised_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interview_feedbacks_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]},{foreignKeyName:"interview_feedbacks_submitted_by_fkey";columns:["submitted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"interview_participants":{Row:{"id": string;
"interview_id": string;
"participant_type": string;
"user_id": string | null;
"external_name": string | null;
"external_email": string | null;
"attendance_status": string;
"created_at": string};Insert:{"id"?: string;
"interview_id": string;
"participant_type": string;
"user_id"?: string | null;
"external_name"?: string | null;
"external_email"?: string | null;
"attendance_status"?: string;
"created_at"?: string};Update:{"id"?: string;
"interview_id"?: string;
"participant_type"?: string;
"user_id"?: string | null;
"external_name"?: string | null;
"external_email"?: string | null;
"attendance_status"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"interview_participants_interview_id_fkey";columns:["interview_id"];isOneToOne:false;referencedRelation:"interviews";referencedColumns:["id"]},{foreignKeyName:"interview_participants_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"interview_reschedules":{Row:{"id": string;
"interview_id": string;
"old_scheduled_at": string;
"new_scheduled_at": string;
"old_timezone": string | null;
"new_timezone": string | null;
"old_mode": string | null;
"new_mode": string | null;
"old_meeting_link": string | null;
"new_meeting_link": string | null;
"old_location": string | null;
"new_location": string | null;
"reason": string;
"rescheduled_by": string;
"rescheduled_at": string};Insert:{"id"?: string;
"interview_id": string;
"old_scheduled_at": string;
"new_scheduled_at": string;
"old_timezone"?: string | null;
"new_timezone"?: string | null;
"old_mode"?: string | null;
"new_mode"?: string | null;
"old_meeting_link"?: string | null;
"new_meeting_link"?: string | null;
"old_location"?: string | null;
"new_location"?: string | null;
"reason": string;
"rescheduled_by": string;
"rescheduled_at"?: string};Update:{"id"?: string;
"interview_id"?: string;
"old_scheduled_at"?: string;
"new_scheduled_at"?: string;
"old_timezone"?: string | null;
"new_timezone"?: string | null;
"old_mode"?: string | null;
"new_mode"?: string | null;
"old_meeting_link"?: string | null;
"new_meeting_link"?: string | null;
"old_location"?: string | null;
"new_location"?: string | null;
"reason"?: string;
"rescheduled_by"?: string;
"rescheduled_at"?: string};Relationships:[{foreignKeyName:"interview_reschedules_interview_id_fkey";columns:["interview_id"];isOneToOne:false;referencedRelation:"interviews";referencedColumns:["id"]},{foreignKeyName:"interview_reschedules_rescheduled_by_fkey";columns:["rescheduled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"interview_status_history":{Row:{"id": number;
"interview_id": string;
"old_status": string | null;
"new_status": string;
"changed_by": string | null;
"reason": string | null;
"metadata": Json | null;
"changed_at": string};Insert:{"id"?: never;
"interview_id": string;
"old_status"?: string | null;
"new_status": string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Update:{"id"?: never;
"interview_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Relationships:[{foreignKeyName:"interview_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interview_status_history_interview_id_fkey";columns:["interview_id"];isOneToOne:false;referencedRelation:"interviews";referencedColumns:["id"]}]};
"interviews":{Row:{"id": string;
"interview_code": string;
"application_id": string;
"submission_candidate_id": string;
"job_id": string;
"company_id": string;
"client_hr_user_id": string;
"round_number": number;
"round_name": string;
"interview_type": string;
"scheduled_at": string;
"duration_minutes": number;
"timezone": string;
"mode": string;
"meeting_provider": string | null;
"meeting_link": string | null;
"location": string | null;
"instructions": string | null;
"status": string;
"scheduled_by": string;
"scheduled_at_created": string;
"started_at": string | null;
"completed_at": string | null;
"cancelled_at": string | null;
"cancelled_by": string | null;
"cancellation_reason": string | null;
"external_calendar_provider": string | null;
"external_calendar_event_id": string | null;
"created_at": string;
"updated_at": string;
"deleted_at": string | null;
"deleted_by": string | null};Insert:{"id"?: string;
"interview_code"?: string;
"application_id": string;
"submission_candidate_id": string;
"job_id": string;
"company_id": string;
"client_hr_user_id": string;
"round_number": number;
"round_name": string;
"interview_type"?: string;
"scheduled_at": string;
"duration_minutes"?: number;
"timezone"?: string;
"mode": string;
"meeting_provider"?: string | null;
"meeting_link"?: string | null;
"location"?: string | null;
"instructions"?: string | null;
"status"?: string;
"scheduled_by": string;
"scheduled_at_created"?: string;
"started_at"?: string | null;
"completed_at"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"external_calendar_provider"?: string | null;
"external_calendar_event_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Update:{"id"?: string;
"interview_code"?: string;
"application_id"?: string;
"submission_candidate_id"?: string;
"job_id"?: string;
"company_id"?: string;
"client_hr_user_id"?: string;
"round_number"?: number;
"round_name"?: string;
"interview_type"?: string;
"scheduled_at"?: string;
"duration_minutes"?: number;
"timezone"?: string;
"mode"?: string;
"meeting_provider"?: string | null;
"meeting_link"?: string | null;
"location"?: string | null;
"instructions"?: string | null;
"status"?: string;
"scheduled_by"?: string;
"scheduled_at_created"?: string;
"started_at"?: string | null;
"completed_at"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"external_calendar_provider"?: string | null;
"external_calendar_event_id"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Relationships:[{foreignKeyName:"interviews_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"interviews_cancelled_by_fkey";columns:["cancelled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interviews_client_hr_user_id_fkey";columns:["client_hr_user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interviews_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"interviews_deleted_by_fkey";columns:["deleted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interviews_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"interviews_scheduled_by_fkey";columns:["scheduled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"interviews_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]}]};
"job_checklists":{Row:{"id": string;
"job_id": string;
"version": number;
"status": string;
"source": string;
"must_have": Json;
"good_to_have": Json;
"tools": Json;
"domain": string;
"exp_required": string;
"top_3_skills": Json;
"checklist_summary": string | null;
"ai_model": string | null;
"ai_response_id": string | null;
"prompt_version": string | null;
"generated_by": string | null;
"generated_at": string | null;
"approved_by": string | null;
"approved_at": string | null;
"created_by": string;
"updated_by": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"job_id": string;
"version": number;
"status"?: string;
"source"?: string;
"must_have"?: Json;
"good_to_have"?: Json;
"tools"?: Json;
"domain": string;
"exp_required": string;
"top_3_skills"?: Json;
"checklist_summary"?: string | null;
"ai_model"?: string | null;
"ai_response_id"?: string | null;
"prompt_version"?: string | null;
"generated_by"?: string | null;
"generated_at"?: string | null;
"approved_by"?: string | null;
"approved_at"?: string | null;
"created_by": string;
"updated_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"job_id"?: string;
"version"?: number;
"status"?: string;
"source"?: string;
"must_have"?: Json;
"good_to_have"?: Json;
"tools"?: Json;
"domain"?: string;
"exp_required"?: string;
"top_3_skills"?: Json;
"checklist_summary"?: string | null;
"ai_model"?: string | null;
"ai_response_id"?: string | null;
"prompt_version"?: string | null;
"generated_by"?: string | null;
"generated_at"?: string | null;
"approved_by"?: string | null;
"approved_at"?: string | null;
"created_by"?: string;
"updated_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"job_checklists_approved_by_fkey";columns:["approved_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"job_checklists_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"job_checklists_generated_by_fkey";columns:["generated_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"job_checklists_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"job_checklists_updated_by_fkey";columns:["updated_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"job_publications":{Row:{"id": string;
"job_id": string;
"checklist_id": string;
"publication_version": number;
"poster_payload": Json;
"broadcast_in_app": boolean;
"broadcast_email": boolean;
"broadcast_whatsapp": boolean;
"broadcast_telegram": boolean;
"broadcast_summary": Json;
"broadcast_queued_at": string | null;
"published_by": string;
"published_at": string;
"created_at": string};Insert:{"id"?: string;
"job_id": string;
"checklist_id": string;
"publication_version": number;
"poster_payload"?: Json;
"broadcast_in_app"?: boolean;
"broadcast_email"?: boolean;
"broadcast_whatsapp"?: boolean;
"broadcast_telegram"?: boolean;
"broadcast_summary"?: Json;
"broadcast_queued_at"?: string | null;
"published_by": string;
"published_at"?: string;
"created_at"?: string};Update:{"id"?: string;
"job_id"?: string;
"checklist_id"?: string;
"publication_version"?: number;
"poster_payload"?: Json;
"broadcast_in_app"?: boolean;
"broadcast_email"?: boolean;
"broadcast_whatsapp"?: boolean;
"broadcast_telegram"?: boolean;
"broadcast_summary"?: Json;
"broadcast_queued_at"?: string | null;
"published_by"?: string;
"published_at"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"job_publications_checklist_id_fkey";columns:["checklist_id"];isOneToOne:false;referencedRelation:"job_checklists";referencedColumns:["id"]},{foreignKeyName:"job_publications_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"job_publications_published_by_fkey";columns:["published_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"job_status_history":{Row:{"id": number;
"job_id": string;
"old_status": string | null;
"new_status": string;
"reason": string | null;
"changed_by": string | null;
"metadata": Json;
"changed_at": string};Insert:{"id"?: never;
"job_id": string;
"old_status"?: string | null;
"new_status": string;
"reason"?: string | null;
"changed_by"?: string | null;
"metadata"?: Json;
"changed_at"?: string};Update:{"id"?: never;
"job_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"reason"?: string | null;
"changed_by"?: string | null;
"metadata"?: Json;
"changed_at"?: string};Relationships:[{foreignKeyName:"job_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"job_status_history_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]}]};
"jobs":{Row:{"id": string;
"job_code": string;
"company_id": string;
"created_by": string;
"assigned_placement_hr": string | null;
"job_title": string;
"role_type": string;
"location_type": string;
"location": string | null;
"country": string | null;
"employment_type": string;
"workplace_type": string;
"experience_min_months": number;
"experience_max_months": number | null;
"salary_min": number | null;
"salary_max": number | null;
"salary_currency": string;
"openings": number;
"jd_text": string;
"application_deadline": string | null;
"status": string;
"submitted_for_checklist_at": string | null;
"published_by": string | null;
"published_at": string | null;
"closed_by": string | null;
"closed_at": string | null;
"notes": string | null;
"created_at": string;
"updated_at": string;
"deleted_at": string | null;
"deleted_by": string | null};Insert:{"id"?: string;
"job_code"?: string;
"company_id": string;
"created_by": string;
"assigned_placement_hr"?: string | null;
"job_title": string;
"role_type": string;
"location_type"?: string;
"location"?: string | null;
"country"?: string | null;
"employment_type"?: string;
"workplace_type"?: string;
"experience_min_months"?: number;
"experience_max_months"?: number | null;
"salary_min"?: number | null;
"salary_max"?: number | null;
"salary_currency"?: string;
"openings"?: number;
"jd_text": string;
"application_deadline"?: string | null;
"status"?: string;
"submitted_for_checklist_at"?: string | null;
"published_by"?: string | null;
"published_at"?: string | null;
"closed_by"?: string | null;
"closed_at"?: string | null;
"notes"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Update:{"id"?: string;
"job_code"?: string;
"company_id"?: string;
"created_by"?: string;
"assigned_placement_hr"?: string | null;
"job_title"?: string;
"role_type"?: string;
"location_type"?: string;
"location"?: string | null;
"country"?: string | null;
"employment_type"?: string;
"workplace_type"?: string;
"experience_min_months"?: number;
"experience_max_months"?: number | null;
"salary_min"?: number | null;
"salary_max"?: number | null;
"salary_currency"?: string;
"openings"?: number;
"jd_text"?: string;
"application_deadline"?: string | null;
"status"?: string;
"submitted_for_checklist_at"?: string | null;
"published_by"?: string | null;
"published_at"?: string | null;
"closed_by"?: string | null;
"closed_at"?: string | null;
"notes"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Relationships:[{foreignKeyName:"jobs_assigned_placement_hr_fkey";columns:["assigned_placement_hr"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"jobs_closed_by_fkey";columns:["closed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"jobs_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"jobs_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"jobs_deleted_by_fkey";columns:["deleted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"jobs_published_by_fkey";columns:["published_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"mock_availability_slots":{Row:{"id": string;
"evaluator_user_id": string;
"created_by": string;
"starts_at": string;
"duration_minutes": number;
"mode": string;
"meeting_link": string | null;
"location": string | null;
"status": string;
"booked_application_id": string | null;
"booked_by": string | null;
"booked_at": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"evaluator_user_id": string;
"created_by": string;
"starts_at": string;
"duration_minutes"?: number;
"mode": string;
"meeting_link"?: string | null;
"location"?: string | null;
"status"?: string;
"booked_application_id"?: string | null;
"booked_by"?: string | null;
"booked_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"evaluator_user_id"?: string;
"created_by"?: string;
"starts_at"?: string;
"duration_minutes"?: number;
"mode"?: string;
"meeting_link"?: string | null;
"location"?: string | null;
"status"?: string;
"booked_application_id"?: string | null;
"booked_by"?: string | null;
"booked_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"mock_availability_slots_booked_application_id_fkey";columns:["booked_application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"mock_availability_slots_booked_by_fkey";columns:["booked_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_availability_slots_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_availability_slots_evaluator_user_id_fkey";columns:["evaluator_user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"mock_interviews":{Row:{"id": string;
"mock_code": string;
"application_id": string;
"submission_candidate_id": string | null;
"availability_slot_id": string | null;
"evaluator_user_id": string;
"scheduled_by": string;
"booking_source": string;
"scheduled_at": string;
"duration_minutes": number;
"mode": string;
"meeting_link": string | null;
"location": string | null;
"status": string;
"student_confirmed_at": string | null;
"started_at": string | null;
"completed_at": string | null;
"cancelled_at": string | null;
"cancelled_by": string | null;
"cancellation_reason": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"mock_code": string;
"application_id": string;
"submission_candidate_id"?: string | null;
"availability_slot_id"?: string | null;
"evaluator_user_id": string;
"scheduled_by": string;
"booking_source": string;
"scheduled_at": string;
"duration_minutes"?: number;
"mode": string;
"meeting_link"?: string | null;
"location"?: string | null;
"status"?: string;
"student_confirmed_at"?: string | null;
"started_at"?: string | null;
"completed_at"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"mock_code"?: string;
"application_id"?: string;
"submission_candidate_id"?: string | null;
"availability_slot_id"?: string | null;
"evaluator_user_id"?: string;
"scheduled_by"?: string;
"booking_source"?: string;
"scheduled_at"?: string;
"duration_minutes"?: number;
"mode"?: string;
"meeting_link"?: string | null;
"location"?: string | null;
"status"?: string;
"student_confirmed_at"?: string | null;
"started_at"?: string | null;
"completed_at"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"mock_interviews_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"mock_interviews_availability_slot_id_fkey";columns:["availability_slot_id"];isOneToOne:false;referencedRelation:"mock_availability_slots";referencedColumns:["id"]},{foreignKeyName:"mock_interviews_cancelled_by_fkey";columns:["cancelled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_interviews_evaluator_user_id_fkey";columns:["evaluator_user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_interviews_scheduled_by_fkey";columns:["scheduled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_interviews_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]}]};
"mock_scorecards":{Row:{"id": string;
"mock_interview_id": string;
"version": number;
"status": string;
"communication_score": number;
"technical_score": number;
"domain_score": number;
"overall_score": number;
"strengths": string | null;
"improvement_areas": string | null;
"evaluator_notes": string | null;
"student_visible_notes": string | null;
"recommendation": string;
"scoring_version": string;
"created_by": string;
"submitted_by": string | null;
"submitted_at": string | null;
"revised_by": string | null;
"revised_at": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"mock_interview_id": string;
"version"?: number;
"status"?: string;
"communication_score": number;
"technical_score": number;
"domain_score": number;
"overall_score": number;
"strengths"?: string | null;
"improvement_areas"?: string | null;
"evaluator_notes"?: string | null;
"student_visible_notes"?: string | null;
"recommendation": string;
"scoring_version"?: string;
"created_by": string;
"submitted_by"?: string | null;
"submitted_at"?: string | null;
"revised_by"?: string | null;
"revised_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"mock_interview_id"?: string;
"version"?: number;
"status"?: string;
"communication_score"?: number;
"technical_score"?: number;
"domain_score"?: number;
"overall_score"?: number;
"strengths"?: string | null;
"improvement_areas"?: string | null;
"evaluator_notes"?: string | null;
"student_visible_notes"?: string | null;
"recommendation"?: string;
"scoring_version"?: string;
"created_by"?: string;
"submitted_by"?: string | null;
"submitted_at"?: string | null;
"revised_by"?: string | null;
"revised_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"mock_scorecards_created_by_fkey";columns:["created_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_scorecards_mock_interview_id_fkey";columns:["mock_interview_id"];isOneToOne:false;referencedRelation:"mock_interviews";referencedColumns:["id"]},{foreignKeyName:"mock_scorecards_revised_by_fkey";columns:["revised_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"mock_scorecards_submitted_by_fkey";columns:["submitted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"notification_delivery_logs":{Row:{"id": string;
"outbox_id": string;
"event_type": string;
"channel": string;
"recipient_user_id": string | null;
"recipient_address": string | null;
"provider": string | null;
"provider_message_id": string | null;
"status": string;
"error_message": string | null;
"metadata": Json;
"delivered_at": string};Insert:{"id"?: string;
"outbox_id": string;
"event_type": string;
"channel": string;
"recipient_user_id"?: string | null;
"recipient_address"?: string | null;
"provider"?: string | null;
"provider_message_id"?: string | null;
"status": string;
"error_message"?: string | null;
"metadata"?: Json;
"delivered_at"?: string};Update:{"id"?: string;
"outbox_id"?: string;
"event_type"?: string;
"channel"?: string;
"recipient_user_id"?: string | null;
"recipient_address"?: string | null;
"provider"?: string | null;
"provider_message_id"?: string | null;
"status"?: string;
"error_message"?: string | null;
"metadata"?: Json;
"delivered_at"?: string};Relationships:[{foreignKeyName:"notification_delivery_logs_outbox_id_fkey";columns:["outbox_id"];isOneToOne:false;referencedRelation:"notification_outbox";referencedColumns:["id"]},{foreignKeyName:"notification_delivery_logs_recipient_user_id_fkey";columns:["recipient_user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"notification_outbox":{Row:{"id": string;
"event_type": string;
"channel": string;
"recipient_user_id": string | null;
"recipient_email": string | null;
"entity_type": string | null;
"entity_id": string | null;
"payload": Json;
"status": string;
"attempts": number;
"max_attempts": number;
"scheduled_for": string;
"processing_started_at": string | null;
"sent_at": string | null;
"failed_at": string | null;
"error_message": string | null;
"dedupe_key": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"event_type": string;
"channel": string;
"recipient_user_id"?: string | null;
"recipient_email"?: string | null;
"entity_type"?: string | null;
"entity_id"?: string | null;
"payload"?: Json;
"status"?: string;
"attempts"?: number;
"max_attempts"?: number;
"scheduled_for"?: string;
"processing_started_at"?: string | null;
"sent_at"?: string | null;
"failed_at"?: string | null;
"error_message"?: string | null;
"dedupe_key"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"event_type"?: string;
"channel"?: string;
"recipient_user_id"?: string | null;
"recipient_email"?: string | null;
"entity_type"?: string | null;
"entity_id"?: string | null;
"payload"?: Json;
"status"?: string;
"attempts"?: number;
"max_attempts"?: number;
"scheduled_for"?: string;
"processing_started_at"?: string | null;
"sent_at"?: string | null;
"failed_at"?: string | null;
"error_message"?: string | null;
"dedupe_key"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"notification_outbox_recipient_user_id_fkey";columns:["recipient_user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"notifications":{Row:{"id": string;
"user_id": string;
"event_type": string;
"title": string;
"message": string;
"entity_type": string | null;
"entity_id": string | null;
"action_url": string | null;
"severity": string;
"is_read": boolean;
"read_at": string | null;
"created_at": string};Insert:{"id"?: string;
"user_id": string;
"event_type": string;
"title": string;
"message": string;
"entity_type"?: string | null;
"entity_id"?: string | null;
"action_url"?: string | null;
"severity"?: string;
"is_read"?: boolean;
"read_at"?: string | null;
"created_at"?: string};Update:{"id"?: string;
"user_id"?: string;
"event_type"?: string;
"title"?: string;
"message"?: string;
"entity_type"?: string | null;
"entity_id"?: string | null;
"action_url"?: string | null;
"severity"?: string;
"is_read"?: boolean;
"read_at"?: string | null;
"created_at"?: string};Relationships:[{foreignKeyName:"notifications_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"offer_status_history":{Row:{"id": number;
"offer_id": string;
"old_status": string | null;
"new_status": string;
"changed_by": string | null;
"reason": string | null;
"metadata": Json | null;
"changed_at": string};Insert:{"id"?: never;
"offer_id": string;
"old_status"?: string | null;
"new_status": string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Update:{"id"?: never;
"offer_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Relationships:[{foreignKeyName:"offer_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"offer_status_history_offer_id_fkey";columns:["offer_id"];isOneToOne:false;referencedRelation:"offers";referencedColumns:["id"]}]};
"offers":{Row:{"id": string;
"offer_code": string | null;
"application_id": string;
"submission_candidate_id": string;
"interview_feedback_id": string;
"student_id": string;
"job_id": string;
"company_id": string;
"designation": string;
"department": string | null;
"employment_type": string | null;
"joining_location": string | null;
"annual_ctc": number | null;
"currency": string;
"joining_date": string | null;
"offer_date": string | null;
"offer_valid_until": string | null;
"probation_period_months": number | null;
"notice_buyout_available": boolean | null;
"notes": string | null;
"bucket_name": string;
"storage_path": string;
"original_file_name": string;
"mime_type": string;
"file_size": number;
"file_hash": string | null;
"status": string;
"uploaded_by": string;
"uploaded_at": string;
"sent_to_student_at": string | null;
"student_decided_at": string | null;
"student_decision_reason": string | null;
"withdrawn_at": string | null;
"withdrawn_by": string | null;
"withdrawal_reason": string | null;
"created_at": string;
"updated_at": string;
"deleted_at": string | null;
"deleted_by": string | null};Insert:{"id"?: string;
"offer_code"?: string | null;
"application_id": string;
"submission_candidate_id": string;
"interview_feedback_id": string;
"student_id": string;
"job_id": string;
"company_id": string;
"designation": string;
"department"?: string | null;
"employment_type"?: string | null;
"joining_location"?: string | null;
"annual_ctc"?: number | null;
"currency"?: string;
"joining_date"?: string | null;
"offer_date"?: string | null;
"offer_valid_until"?: string | null;
"probation_period_months"?: number | null;
"notice_buyout_available"?: boolean | null;
"notes"?: string | null;
"bucket_name"?: string;
"storage_path": string;
"original_file_name": string;
"mime_type": string;
"file_size": number;
"file_hash"?: string | null;
"status"?: string;
"uploaded_by": string;
"uploaded_at"?: string;
"sent_to_student_at"?: string | null;
"student_decided_at"?: string | null;
"student_decision_reason"?: string | null;
"withdrawn_at"?: string | null;
"withdrawn_by"?: string | null;
"withdrawal_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Update:{"id"?: string;
"offer_code"?: string | null;
"application_id"?: string;
"submission_candidate_id"?: string;
"interview_feedback_id"?: string;
"student_id"?: string;
"job_id"?: string;
"company_id"?: string;
"designation"?: string;
"department"?: string | null;
"employment_type"?: string | null;
"joining_location"?: string | null;
"annual_ctc"?: number | null;
"currency"?: string;
"joining_date"?: string | null;
"offer_date"?: string | null;
"offer_valid_until"?: string | null;
"probation_period_months"?: number | null;
"notice_buyout_available"?: boolean | null;
"notes"?: string | null;
"bucket_name"?: string;
"storage_path"?: string;
"original_file_name"?: string;
"mime_type"?: string;
"file_size"?: number;
"file_hash"?: string | null;
"status"?: string;
"uploaded_by"?: string;
"uploaded_at"?: string;
"sent_to_student_at"?: string | null;
"student_decided_at"?: string | null;
"student_decision_reason"?: string | null;
"withdrawn_at"?: string | null;
"withdrawn_by"?: string | null;
"withdrawal_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"deleted_at"?: string | null;
"deleted_by"?: string | null};Relationships:[{foreignKeyName:"offers_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"offers_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"offers_deleted_by_fkey";columns:["deleted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"offers_interview_feedback_id_fkey";columns:["interview_feedback_id"];isOneToOne:false;referencedRelation:"interview_feedbacks";referencedColumns:["id"]},{foreignKeyName:"offers_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"offers_student_id_fkey";columns:["student_id"];isOneToOne:false;referencedRelation:"student_profiles";referencedColumns:["id"]},{foreignKeyName:"offers_submission_candidate_id_fkey";columns:["submission_candidate_id"];isOneToOne:false;referencedRelation:"submission_candidates";referencedColumns:["id"]},{foreignKeyName:"offers_uploaded_by_fkey";columns:["uploaded_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"offers_withdrawn_by_fkey";columns:["withdrawn_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"operational_alerts":{Row:{"id": string;
"alert_type": string;
"entity_type": string;
"entity_id": string;
"severity": string;
"title": string;
"description": string | null;
"status": string;
"assigned_to": string | null;
"due_at": string | null;
"acknowledged_at": string | null;
"acknowledged_by": string | null;
"resolved_at": string | null;
"resolved_by": string | null;
"resolution_notes": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"alert_type": string;
"entity_type": string;
"entity_id": string;
"severity"?: string;
"title": string;
"description"?: string | null;
"status"?: string;
"assigned_to"?: string | null;
"due_at"?: string | null;
"acknowledged_at"?: string | null;
"acknowledged_by"?: string | null;
"resolved_at"?: string | null;
"resolved_by"?: string | null;
"resolution_notes"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"alert_type"?: string;
"entity_type"?: string;
"entity_id"?: string;
"severity"?: string;
"title"?: string;
"description"?: string | null;
"status"?: string;
"assigned_to"?: string | null;
"due_at"?: string | null;
"acknowledged_at"?: string | null;
"acknowledged_by"?: string | null;
"resolved_at"?: string | null;
"resolved_by"?: string | null;
"resolution_notes"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"operational_alerts_acknowledged_by_fkey";columns:["acknowledged_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"operational_alerts_assigned_to_fkey";columns:["assigned_to"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"operational_alerts_resolved_by_fkey";columns:["resolved_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"parsed_cv_profiles":{Row:{"id": string;
"cv_id": string;
"parser_version": string;
"extraction_version": string;
"raw_text": string;
"raw_text_sha256": string;
"page_count": number | null;
"word_count": number;
"character_count": number;
"extracted_profile": Json;
"ai_model": string | null;
"ai_response_id": string | null;
"created_at": string};Insert:{"id"?: string;
"cv_id": string;
"parser_version": string;
"extraction_version": string;
"raw_text": string;
"raw_text_sha256": string;
"page_count"?: number | null;
"word_count"?: number;
"character_count"?: number;
"extracted_profile": Json;
"ai_model"?: string | null;
"ai_response_id"?: string | null;
"created_at"?: string};Update:{"id"?: string;
"cv_id"?: string;
"parser_version"?: string;
"extraction_version"?: string;
"raw_text"?: string;
"raw_text_sha256"?: string;
"page_count"?: number | null;
"word_count"?: number;
"character_count"?: number;
"extracted_profile"?: Json;
"ai_model"?: string | null;
"ai_response_id"?: string | null;
"created_at"?: string};Relationships:[{foreignKeyName:"parsed_cv_profiles_cv_id_fkey";columns:["cv_id"];isOneToOne:false;referencedRelation:"student_cvs";referencedColumns:["id"]}]};
"permissions":{Row:{"id": string;
"code": string;
"name": string;
"description": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"code": string;
"name": string;
"description"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"code"?: string;
"name"?: string;
"description"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[]};
"placement_hr_profiles":{Row:{"id": string;
"user_id": string;
"employee_code": string | null;
"designation": string | null;
"department": string | null;
"work_email": string | null;
"work_phone": string | null;
"is_active": boolean;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"user_id": string;
"employee_code"?: string | null;
"designation"?: string | null;
"department"?: string | null;
"work_email"?: string | null;
"work_phone"?: string | null;
"is_active"?: boolean;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"user_id"?: string;
"employee_code"?: string | null;
"designation"?: string | null;
"department"?: string | null;
"work_email"?: string | null;
"work_phone"?: string | null;
"is_active"?: boolean;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"placement_hr_profiles_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"placement_status_history":{Row:{"id": number;
"placement_id": string;
"old_status": string | null;
"new_status": string;
"changed_by": string | null;
"reason": string | null;
"metadata": Json | null;
"changed_at": string};Insert:{"id"?: never;
"placement_id": string;
"old_status"?: string | null;
"new_status": string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Update:{"id"?: never;
"placement_id"?: string;
"old_status"?: string | null;
"new_status"?: string;
"changed_by"?: string | null;
"reason"?: string | null;
"metadata"?: Json | null;
"changed_at"?: string};Relationships:[{foreignKeyName:"placement_status_history_changed_by_fkey";columns:["changed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"placement_status_history_placement_id_fkey";columns:["placement_id"];isOneToOne:false;referencedRelation:"placements";referencedColumns:["id"]}]};
"placements":{Row:{"id": string;
"placement_code": string | null;
"application_id": string;
"offer_id": string;
"student_id": string;
"job_id": string;
"company_id": string;
"placed_designation": string;
"placed_department": string | null;
"joining_location": string | null;
"annual_ctc": number | null;
"currency": string;
"joining_date": string | null;
"placement_status": string;
"placed_by": string;
"placed_at": string;
"joined_at": string | null;
"closed_at": string | null;
"closed_by": string | null;
"closure_reason": string | null;
"notes": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"placement_code"?: string | null;
"application_id": string;
"offer_id": string;
"student_id": string;
"job_id": string;
"company_id": string;
"placed_designation": string;
"placed_department"?: string | null;
"joining_location"?: string | null;
"annual_ctc"?: number | null;
"currency"?: string;
"joining_date"?: string | null;
"placement_status"?: string;
"placed_by": string;
"placed_at"?: string;
"joined_at"?: string | null;
"closed_at"?: string | null;
"closed_by"?: string | null;
"closure_reason"?: string | null;
"notes"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"placement_code"?: string | null;
"application_id"?: string;
"offer_id"?: string;
"student_id"?: string;
"job_id"?: string;
"company_id"?: string;
"placed_designation"?: string;
"placed_department"?: string | null;
"joining_location"?: string | null;
"annual_ctc"?: number | null;
"currency"?: string;
"joining_date"?: string | null;
"placement_status"?: string;
"placed_by"?: string;
"placed_at"?: string;
"joined_at"?: string | null;
"closed_at"?: string | null;
"closed_by"?: string | null;
"closure_reason"?: string | null;
"notes"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"placements_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"placements_closed_by_fkey";columns:["closed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"placements_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"placements_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"placements_offer_id_fkey";columns:["offer_id"];isOneToOne:false;referencedRelation:"offers";referencedColumns:["id"]},{foreignKeyName:"placements_placed_by_fkey";columns:["placed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"placements_student_id_fkey";columns:["student_id"];isOneToOne:false;referencedRelation:"student_profiles";referencedColumns:["id"]}]};
"profiles":{Row:{"id": string;
"first_name": string | null;
"last_name": string | null;
"email": string;
"phone": string | null;
"avatar_url": string | null;
"account_status": string;
"approved_at": string | null;
"approved_by": string | null;
"rejected_at": string | null;
"rejected_by": string | null;
"rejection_reason": string | null;
"suspended_at": string | null;
"suspended_by": string | null;
"suspension_reason": string | null;
"last_login_at": string | null;
"created_at": string;
"updated_at": string;
"inactive_at": string | null;
"inactive_by": string | null;
"inactivation_reason": string | null};Insert:{"id": string;
"first_name"?: string | null;
"last_name"?: string | null;
"email": string;
"phone"?: string | null;
"avatar_url"?: string | null;
"account_status"?: string;
"approved_at"?: string | null;
"approved_by"?: string | null;
"rejected_at"?: string | null;
"rejected_by"?: string | null;
"rejection_reason"?: string | null;
"suspended_at"?: string | null;
"suspended_by"?: string | null;
"suspension_reason"?: string | null;
"last_login_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"inactive_at"?: string | null;
"inactive_by"?: string | null;
"inactivation_reason"?: string | null};Update:{"id"?: string;
"first_name"?: string | null;
"last_name"?: string | null;
"email"?: string;
"phone"?: string | null;
"avatar_url"?: string | null;
"account_status"?: string;
"approved_at"?: string | null;
"approved_by"?: string | null;
"rejected_at"?: string | null;
"rejected_by"?: string | null;
"rejection_reason"?: string | null;
"suspended_at"?: string | null;
"suspended_by"?: string | null;
"suspension_reason"?: string | null;
"last_login_at"?: string | null;
"created_at"?: string;
"updated_at"?: string;
"inactive_at"?: string | null;
"inactive_by"?: string | null;
"inactivation_reason"?: string | null};Relationships:[{foreignKeyName:"profiles_approved_by_fkey";columns:["approved_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"profiles_id_fkey";columns:["id"];isOneToOne:false;referencedRelation:"users";referencedColumns:["id"]},{foreignKeyName:"profiles_inactive_by_fkey";columns:["inactive_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"profiles_rejected_by_fkey";columns:["rejected_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"profiles_suspended_by_fkey";columns:["suspended_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"rate_limit_buckets":{Row:{"bucket_key": string;
"window_started_at": string;
"request_count": number;
"updated_at": string};Insert:{"bucket_key": string;
"window_started_at": string;
"request_count"?: number;
"updated_at"?: string};Update:{"bucket_key"?: string;
"window_started_at"?: string;
"request_count"?: number;
"updated_at"?: string};Relationships:[]};
"release_health_events":{Row:{"id": string;
"release_id": string;
"check_type": string;
"status": string;
"details": Json;
"checked_at": string};Insert:{"id"?: string;
"release_id": string;
"check_type": string;
"status": string;
"details"?: Json;
"checked_at"?: string};Update:{"id"?: string;
"release_id"?: string;
"check_type"?: string;
"status"?: string;
"details"?: Json;
"checked_at"?: string};Relationships:[{foreignKeyName:"release_health_events_release_id_fkey";columns:["release_id"];isOneToOne:false;referencedRelation:"system_releases";referencedColumns:["id"]}]};
"role_permissions":{Row:{"role_id": string;
"permission_id": string;
"created_at": string};Insert:{"role_id": string;
"permission_id": string;
"created_at"?: string};Update:{"role_id"?: string;
"permission_id"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"role_permissions_permission_id_fkey";columns:["permission_id"];isOneToOne:false;referencedRelation:"permissions";referencedColumns:["id"]},{foreignKeyName:"role_permissions_role_id_fkey";columns:["role_id"];isOneToOne:false;referencedRelation:"roles";referencedColumns:["id"]}]};
"roles":{Row:{"id": string;
"name": string;
"display_name": string;
"description": string | null;
"is_system": boolean;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"name": string;
"display_name": string;
"description"?: string | null;
"is_system"?: boolean;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"name"?: string;
"display_name"?: string;
"description"?: string | null;
"is_system"?: boolean;
"created_at"?: string;
"updated_at"?: string};Relationships:[]};
"student_cvs":{Row:{"id": string;
"student_id": string;
"storage_path": string;
"original_file_name": string;
"mime_type": string;
"file_size": number;
"file_extension": string;
"is_primary": boolean;
"parsing_status": string;
"parse_error": string | null;
"uploaded_by": string;
"uploaded_at": string;
"parsed_at": string | null;
"deleted_at": string | null;
"deleted_by": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"student_id": string;
"storage_path": string;
"original_file_name": string;
"mime_type": string;
"file_size": number;
"file_extension": string;
"is_primary"?: boolean;
"parsing_status"?: string;
"parse_error"?: string | null;
"uploaded_by": string;
"uploaded_at"?: string;
"parsed_at"?: string | null;
"deleted_at"?: string | null;
"deleted_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"student_id"?: string;
"storage_path"?: string;
"original_file_name"?: string;
"mime_type"?: string;
"file_size"?: number;
"file_extension"?: string;
"is_primary"?: boolean;
"parsing_status"?: string;
"parse_error"?: string | null;
"uploaded_by"?: string;
"uploaded_at"?: string;
"parsed_at"?: string | null;
"deleted_at"?: string | null;
"deleted_by"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"student_cvs_deleted_by_fkey";columns:["deleted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"student_cvs_student_id_fkey";columns:["student_id"];isOneToOne:false;referencedRelation:"student_profiles";referencedColumns:["id"]},{foreignKeyName:"student_cvs_uploaded_by_fkey";columns:["uploaded_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"student_profiles":{Row:{"id": string;
"user_id": string;
"enrollment_id": string;
"verification_status": string;
"verification_source": string | null;
"verification_reference": string | null;
"verification_at": string | null;
"verified_by": string | null;
"verification_reason": string | null;
"first_name": string | null;
"last_name": string | null;
"phone": string | null;
"headline": string | null;
"summary": string | null;
"location": string | null;
"city": string | null;
"state": string | null;
"country": string | null;
"postal_code": string | null;
"qualification": string | null;
"graduation_year": number | null;
"specialization": string | null;
"total_experience_months": number;
"current_company": string | null;
"current_designation": string | null;
"current_ctc": number | null;
"current_ctc_currency": string | null;
"notice_period_days": number | null;
"preferred_role": string | null;
"preferred_location": string | null;
"willing_to_relocate": boolean | null;
"linkedin_url": string | null;
"github_url": string | null;
"portfolio_url": string | null;
"profile_completion": number;
"profile_status": string;
"created_at": string;
"updated_at": string;
"skills": Json;
"preferred_workplace_type": string | null;
"availability_status": string;
"expected_ctc": number | null};Insert:{"id"?: string;
"user_id": string;
"enrollment_id": string;
"verification_status"?: string;
"verification_source"?: string | null;
"verification_reference"?: string | null;
"verification_at"?: string | null;
"verified_by"?: string | null;
"verification_reason"?: string | null;
"first_name"?: string | null;
"last_name"?: string | null;
"phone"?: string | null;
"headline"?: string | null;
"summary"?: string | null;
"location"?: string | null;
"city"?: string | null;
"state"?: string | null;
"country"?: string | null;
"postal_code"?: string | null;
"qualification"?: string | null;
"graduation_year"?: number | null;
"specialization"?: string | null;
"total_experience_months"?: number;
"current_company"?: string | null;
"current_designation"?: string | null;
"current_ctc"?: number | null;
"current_ctc_currency"?: string | null;
"notice_period_days"?: number | null;
"preferred_role"?: string | null;
"preferred_location"?: string | null;
"willing_to_relocate"?: boolean | null;
"linkedin_url"?: string | null;
"github_url"?: string | null;
"portfolio_url"?: string | null;
"profile_completion"?: number;
"profile_status"?: string;
"created_at"?: string;
"updated_at"?: string;
"skills"?: Json;
"preferred_workplace_type"?: string | null;
"availability_status"?: string;
"expected_ctc"?: number | null};Update:{"id"?: string;
"user_id"?: string;
"enrollment_id"?: string;
"verification_status"?: string;
"verification_source"?: string | null;
"verification_reference"?: string | null;
"verification_at"?: string | null;
"verified_by"?: string | null;
"verification_reason"?: string | null;
"first_name"?: string | null;
"last_name"?: string | null;
"phone"?: string | null;
"headline"?: string | null;
"summary"?: string | null;
"location"?: string | null;
"city"?: string | null;
"state"?: string | null;
"country"?: string | null;
"postal_code"?: string | null;
"qualification"?: string | null;
"graduation_year"?: number | null;
"specialization"?: string | null;
"total_experience_months"?: number;
"current_company"?: string | null;
"current_designation"?: string | null;
"current_ctc"?: number | null;
"current_ctc_currency"?: string | null;
"notice_period_days"?: number | null;
"preferred_role"?: string | null;
"preferred_location"?: string | null;
"willing_to_relocate"?: boolean | null;
"linkedin_url"?: string | null;
"github_url"?: string | null;
"portfolio_url"?: string | null;
"profile_completion"?: number;
"profile_status"?: string;
"created_at"?: string;
"updated_at"?: string;
"skills"?: Json;
"preferred_workplace_type"?: string | null;
"availability_status"?: string;
"expected_ctc"?: number | null};Relationships:[{foreignKeyName:"student_profiles_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"student_profiles_verified_by_fkey";columns:["verified_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"submission_candidates":{Row:{"id": string;
"submission_id": string;
"application_id": string;
"student_id": string;
"cv_id": string;
"status": string;
"candidate_snapshot": Json;
"submitted_match_score": number;
"submitted_ats_score": number | null;
"current_mock_score": number | null;
"client_decision_at": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"submission_id": string;
"application_id": string;
"student_id": string;
"cv_id": string;
"status"?: string;
"candidate_snapshot"?: Json;
"submitted_match_score": number;
"submitted_ats_score"?: number | null;
"current_mock_score"?: number | null;
"client_decision_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"submission_id"?: string;
"application_id"?: string;
"student_id"?: string;
"cv_id"?: string;
"status"?: string;
"candidate_snapshot"?: Json;
"submitted_match_score"?: number;
"submitted_ats_score"?: number | null;
"current_mock_score"?: number | null;
"client_decision_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"submission_candidates_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"submission_candidates_cv_id_fkey";columns:["cv_id"];isOneToOne:false;referencedRelation:"student_cvs";referencedColumns:["id"]},{foreignKeyName:"submission_candidates_student_id_fkey";columns:["student_id"];isOneToOne:false;referencedRelation:"student_profiles";referencedColumns:["id"]},{foreignKeyName:"submission_candidates_submission_id_fkey";columns:["submission_id"];isOneToOne:false;referencedRelation:"submissions";referencedColumns:["id"]}]};
"submissions":{Row:{"id": string;
"submission_code": string;
"job_id": string;
"company_id": string;
"submitted_by": string;
"status": string;
"notes": string | null;
"candidate_count": number;
"submitted_at": string | null;
"acknowledged_at": string | null;
"acknowledged_by": string | null;
"cancelled_at": string | null;
"cancelled_by": string | null;
"cancellation_reason": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"submission_code": string;
"job_id": string;
"company_id": string;
"submitted_by": string;
"status"?: string;
"notes"?: string | null;
"candidate_count"?: number;
"submitted_at"?: string | null;
"acknowledged_at"?: string | null;
"acknowledged_by"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"submission_code"?: string;
"job_id"?: string;
"company_id"?: string;
"submitted_by"?: string;
"status"?: string;
"notes"?: string | null;
"candidate_count"?: number;
"submitted_at"?: string | null;
"acknowledged_at"?: string | null;
"acknowledged_by"?: string | null;
"cancelled_at"?: string | null;
"cancelled_by"?: string | null;
"cancellation_reason"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"submissions_acknowledged_by_fkey";columns:["acknowledged_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"submissions_cancelled_by_fkey";columns:["cancelled_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"submissions_company_id_fkey";columns:["company_id"];isOneToOne:false;referencedRelation:"companies";referencedColumns:["id"]},{foreignKeyName:"submissions_job_id_fkey";columns:["job_id"];isOneToOne:false;referencedRelation:"jobs";referencedColumns:["id"]},{foreignKeyName:"submissions_submitted_by_fkey";columns:["submitted_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"system_releases":{Row:{"id": string;
"release_version": string;
"schema_version": string;
"release_name": string;
"status": string;
"deployed_at": string;
"deployed_by": string | null;
"git_commit": string | null;
"release_notes": string | null};Insert:{"id"?: string;
"release_version": string;
"schema_version": string;
"release_name": string;
"status": string;
"deployed_at"?: string;
"deployed_by"?: string | null;
"git_commit"?: string | null;
"release_notes"?: string | null};Update:{"id"?: string;
"release_version"?: string;
"schema_version"?: string;
"release_name"?: string;
"status"?: string;
"deployed_at"?: string;
"deployed_by"?: string | null;
"git_commit"?: string | null;
"release_notes"?: string | null};Relationships:[{foreignKeyName:"system_releases_deployed_by_fkey";columns:["deployed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"system_schema_versions":{Row:{"version": string;
"description": string;
"applied_at": string};Insert:{"version": string;
"description": string;
"applied_at"?: string};Update:{"version"?: string;
"description"?: string;
"applied_at"?: string};Relationships:[]};
"uat_runs":{Row:{"id": string;
"run_code": string;
"environment": string;
"release_version": string;
"started_at": string;
"completed_at": string | null;
"status": string;
"executed_by": string | null;
"total_tests": number;
"passed_tests": number;
"failed_tests": number;
"notes": string | null};Insert:{"id"?: string;
"run_code": string;
"environment": string;
"release_version": string;
"started_at"?: string;
"completed_at"?: string | null;
"status"?: string;
"executed_by"?: string | null;
"total_tests"?: number;
"passed_tests"?: number;
"failed_tests"?: number;
"notes"?: string | null};Update:{"id"?: string;
"run_code"?: string;
"environment"?: string;
"release_version"?: string;
"started_at"?: string;
"completed_at"?: string | null;
"status"?: string;
"executed_by"?: string | null;
"total_tests"?: number;
"passed_tests"?: number;
"failed_tests"?: number;
"notes"?: string | null};Relationships:[{foreignKeyName:"uat_runs_executed_by_fkey";columns:["executed_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"uat_test_results":{Row:{"id": string;
"uat_run_id": string;
"test_code": string;
"area": string;
"actor_role": string | null;
"description": string;
"expected_result": string;
"actual_result": string | null;
"status": string;
"evidence": string | null;
"executed_at": string};Insert:{"id"?: string;
"uat_run_id": string;
"test_code": string;
"area": string;
"actor_role"?: string | null;
"description": string;
"expected_result": string;
"actual_result"?: string | null;
"status": string;
"evidence"?: string | null;
"executed_at"?: string};Update:{"id"?: string;
"uat_run_id"?: string;
"test_code"?: string;
"area"?: string;
"actor_role"?: string | null;
"description"?: string;
"expected_result"?: string;
"actual_result"?: string | null;
"status"?: string;
"evidence"?: string | null;
"executed_at"?: string};Relationships:[{foreignKeyName:"uat_test_results_uat_run_id_fkey";columns:["uat_run_id"];isOneToOne:false;referencedRelation:"uat_runs";referencedColumns:["id"]}]};
"user_roles":{Row:{"id": string;
"user_id": string;
"role_id": string;
"assigned_by": string | null;
"assigned_at": string;
"created_at": string};Insert:{"id"?: string;
"user_id": string;
"role_id": string;
"assigned_by"?: string | null;
"assigned_at"?: string;
"created_at"?: string};Update:{"id"?: string;
"user_id"?: string;
"role_id"?: string;
"assigned_by"?: string | null;
"assigned_at"?: string;
"created_at"?: string};Relationships:[{foreignKeyName:"user_roles_assigned_by_fkey";columns:["assigned_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"user_roles_role_id_fkey";columns:["role_id"];isOneToOne:false;referencedRelation:"roles";referencedColumns:["id"]},{foreignKeyName:"user_roles_user_id_fkey";columns:["user_id"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
"verification_assignments":{Row:{"id": string;
"application_id": string;
"assigned_to": string;
"assigned_by": string;
"assignment_type": string;
"status": string;
"claimed_at": string;
"expires_at": string;
"completed_at": string | null;
"released_at": string | null;
"created_at": string;
"updated_at": string};Insert:{"id"?: string;
"application_id": string;
"assigned_to": string;
"assigned_by": string;
"assignment_type"?: string;
"status"?: string;
"claimed_at"?: string;
"expires_at"?: string;
"completed_at"?: string | null;
"released_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Update:{"id"?: string;
"application_id"?: string;
"assigned_to"?: string;
"assigned_by"?: string;
"assignment_type"?: string;
"status"?: string;
"claimed_at"?: string;
"expires_at"?: string;
"completed_at"?: string | null;
"released_at"?: string | null;
"created_at"?: string;
"updated_at"?: string};Relationships:[{foreignKeyName:"verification_assignments_application_id_fkey";columns:["application_id"];isOneToOne:false;referencedRelation:"applications";referencedColumns:["id"]},{foreignKeyName:"verification_assignments_assigned_by_fkey";columns:["assigned_by"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]},{foreignKeyName:"verification_assignments_assigned_to_fkey";columns:["assigned_to"];isOneToOne:false;referencedRelation:"profiles";referencedColumns:["id"]}]};
};Views:{"analytics_application_funnel":{Row:{"total_applications": number | null;
"verified_or_beyond": number | null;
"submitted_to_client": number | null;
"shortlisted": number | null;
"interview_stage": number | null;
"selected": number | null;
"offer_received": number | null;
"placed": number | null};Relationships:[]};
"analytics_feedback_sla":{Row:{"interview_id": string | null;
"application_id": string | null;
"company_id": string | null;
"completed_at": string | null;
"feedback_id": string | null;
"submitted_at": string | null;
"feedback_due_at": string | null;
"sla_status": string | null;
"elapsed_hours": number | null};Relationships:[]};
"analytics_placement_summary":{Row:{"total_placements": number | null;
"placed_pending_joining": number | null;
"joined": number | null;
"closed": number | null;
"average_ctc_inr": number | null;
"highest_ctc_inr": number | null;
"total_ctc_inr": number | null};Relationships:[]};
"analytics_submission_sla":{Row:{"submission_id": string | null;
"job_id": string | null;
"company_id": string | null;
"job_created_at": string | null;
"submitted_at": string | null;
"turnaround_hours": number | null;
"within_24h": boolean | null};Relationships:[]};
"application_effective_scores":{Row:{"application_id": string | null;
"automated_match_score": number | null;
"verified_match_score": number | null;
"effective_match_score": number | null;
"automated_ats_score": number | null;
"verified_ats_score": number | null;
"effective_ats_score": number | null};Relationships:[]};
};Functions:{"approve_job_checklist":{Args:{"p_checklist_id":string | null;"p_actor_id":string | null}|{"p_checklist_id":string | null};Returns:string};
"begin_application_scoring":{Args:{"p_application_id":string | null;"p_actor_id":string | null};Returns:string};
"book_mock_slot":{Args:{"p_application_id":string | null;"p_slot_id":string | null};Returns:string};
"cancel_client_interview":{Args:{"p_interview_id":string | null;"p_reason":string | null};Returns:undefined};
"cancel_mock_interview":{Args:{"p_mock_id":string | null;"p_reason":string | null};Returns:undefined};
"claim_application_verification":{Args:{"p_application_id":string | null};Returns:string};
"claim_notification_outbox":{Args:{"p_limit"?:number | null};Returns:Database["public"]["Tables"]["notification_outbox"]["Row"][]};
"cleanup_rate_limits":{Args:Record<PropertyKey, never>;Returns:number};
"client_decide_candidate":{Args:{"p_submission_candidate_id":string | null;"p_decision":string | null;"p_reason_code"?:string | null;"p_reason"?:string | null};Returns:string};
"close_placement":{Args:{"p_placement_id":string | null;"p_reason":string | null};Returns:undefined};
"complete_application_scoring":{Args:{"p_application_id":string | null;"p_run_id":string | null;"p_actor_id":string | null;"p_parsed_cv_profile_id":string | null;"p_match":Json | null;"p_ats":Json | null;"p_engine_version":string | null;"p_matches":Json | null};Returns:string};
"complete_client_interview":{Args:{"p_interview_id":string | null};Returns:undefined};
"confirm_placement":{Args:{"p_offer_id":string | null;"p_notes"?:string | null};Returns:string};
"consume_rate_limit":{Args:{"p_bucket_key":string | null;"p_limit":number | null;"p_window_seconds":number | null};Returns:Json};
"create_client_submission":{Args:{"p_job_id":string | null;"p_application_ids":(string)[] | null;"p_notes"?:string | null};Returns:string};
"create_mock_slot":{Args:{"p_evaluator_user_id":string | null;"p_starts_at":string | null;"p_duration_minutes":number | null;"p_mode":string | null;"p_meeting_link"?:string | null;"p_location"?:string | null};Returns:string};
"create_platform_user":{Args:{"p_user_id":string | null;"p_role_id":string | null;"p_assigned_by":string | null;"p_first_name":string | null;"p_last_name":string | null;"p_phone":string | null;"p_email":string | null;"p_role":string | null;"p_enrollment_id":string | null;"p_verification_reference":string | null;"p_verified_by":string | null;"p_company_id":string | null;"p_work_email":string | null};Returns:string};
"create_student_application":{Args:{"p_job_id":string | null;"p_student_id":string | null;"p_cv_id":string | null;"p_actor_id":string | null};Returns:string};
"current_profile_id":{Args:Record<PropertyKey, never>;Returns:string};
"current_user_roles":{Args:Record<PropertyKey, never>;Returns:(string)[]};
"enforce_application_state_transition":{Args:Record<PropertyKey, never>;Returns:string};
"fail_application_scoring":{Args:{"p_application_id":string | null;"p_run_id":string | null;"p_actor_id":string | null;"p_error":string | null};Returns:undefined};
"finalize_application_verification":{Args:{"p_application_id":string | null;"p_decision":string | null;"p_verified_match_score"?:number | null;"p_verified_ats_score"?:number | null;"p_notes"?:string | null;"p_reason"?:string | null}|{"p_application_id":string | null;"p_decision":string | null;"p_verified_match_score"?:number | null;"p_verified_ats_score"?:number | null;"p_must_have_verified"?:boolean | null;"p_cv_verified"?:boolean | null;"p_experience_verified"?:boolean | null;"p_domain_verified"?:boolean | null;"p_notes"?:string | null;"p_reason"?:string | null;"p_update_request"?:string | null};Returns:string};
"finish_notification_attempt":{Args:{"p_outbox_id":string | null;"p_attempt":number | null;"p_error"?:string | null};Returns:boolean};
"generate_feedback_code":{Args:Record<PropertyKey, never>;Returns:string};
"generate_job_code":{Args:Record<PropertyKey, never>;Returns:string};
"generate_offer_code":{Args:Record<PropertyKey, never>;Returns:string};
"generate_placement_code":{Args:Record<PropertyKey, never>;Returns:string};
"get_client_company_analytics":{Args:Record<PropertyKey, never>;Returns:Json};
"handle_new_auth_user":{Args:Record<PropertyKey, never>;Returns:string};
"has_role":{Args:{"requested_role":string | null};Returns:boolean};
"is_admin":{Args:Record<PropertyKey, never>;Returns:boolean};
"is_super_admin":{Args:Record<PropertyKey, never>;Returns:boolean};
"mark_all_notifications_read":{Args:Record<PropertyKey, never>;Returns:number};
"mark_notification_failed":{Args:{"p_outbox_id":string | null;"p_error":string | null};Returns:undefined};
"mark_notification_read":{Args:{"p_notification_id":string | null};Returns:undefined};
"mark_notification_sent":{Args:{"p_outbox_id":string | null};Returns:undefined};
"mark_placement_joined":{Args:{"p_placement_id":string | null;"p_joined_at"?:string | null};Returns:undefined};
"next_mock_code":{Args:Record<PropertyKey, never>;Returns:string};
"next_submission_code":{Args:Record<PropertyKey, never>;Returns:string};
"publish_job_stage4":{Args:{"p_job_id":string | null;"p_actor_id":string | null;"p_poster_payload":Json | null;"p_broadcast_options":Json | null};Returns:string};
"recover_stuck_notifications":{Args:Record<PropertyKey, never>;Returns:number};
"register_offer":{Args:{"p_application_id":string | null;"p_feedback_id":string | null;"p_designation":string | null;"p_department":string | null;"p_employment_type":string | null;"p_joining_location":string | null;"p_annual_ctc":number | null;"p_currency":string | null;"p_joining_date":string | null;"p_offer_date":string | null;"p_offer_valid_until":string | null;"p_probation_period_months":number | null;"p_notice_buyout_available":boolean | null;"p_notes":string | null;"p_bucket_name":string | null;"p_storage_path":string | null;"p_original_file_name":string | null;"p_mime_type":string | null;"p_file_size":number | null;"p_file_hash":string | null};Returns:string};
"release_application_verification":{Args:{"p_application_id":string | null};Returns:undefined};
"reschedule_client_interview":{Args:{"p_interview_id":string | null;"p_new_scheduled_at":string | null;"p_new_timezone":string | null;"p_new_mode":string | null;"p_new_meeting_provider":string | null;"p_new_meeting_link":string | null;"p_new_location":string | null;"p_reason":string | null};Returns:undefined};
"revise_interview_feedback":{Args:{"p_feedback_id":string | null;"p_rating":number | null;"p_decision":string | null;"p_reason_code"?:string | null;"p_comments"?:string | null;"p_visible_to_student"?:boolean | null;"p_revision_reason"?:string | null};Returns:string};
"save_generated_job_checklist":{Args:{"p_job_id":string | null;"p_actor_id":string | null;"p_payload":Json | null;"p_ai_model":string | null;"p_ai_response_id":string | null;"p_prompt_version":string | null};Returns:string};
"schedule_client_interview":{Args:{"p_submission_candidate_id":string | null;"p_round_name":string | null;"p_interview_type":string | null;"p_scheduled_at":string | null;"p_duration_minutes":number | null;"p_timezone":string | null;"p_mode":string | null;"p_meeting_provider":string | null;"p_meeting_link":string | null;"p_location":string | null;"p_instructions":string | null};Returns:string};
"schedule_mock_interview":{Args:{"p_application_id":string | null;"p_evaluator_user_id":string | null;"p_scheduled_at":string | null;"p_duration_minutes":number | null;"p_mode":string | null;"p_meeting_link"?:string | null;"p_location"?:string | null};Returns:string};
"set_primary_student_cv":{Args:{"p_cv_id":string | null;"p_actor_id":string | null};Returns:string};
"set_updated_at":{Args:Record<PropertyKey, never>;Returns:string};
"soft_delete_student_cv":{Args:{"p_cv_id":string | null;"p_actor_id":string | null};Returns:string};
"stage09_is_admin":{Args:{"p_user":string | null};Returns:boolean};
"stage09_is_placement_hr":{Args:{"p_user":string | null};Returns:boolean};
"start_mock_interview":{Args:{"p_mock_id":string | null};Returns:undefined};
"student_decide_offer":{Args:{"p_offer_id":string | null;"p_decision":string | null;"p_reason"?:string | null};Returns:undefined};
"submit_interview_feedback":{Args:{"p_interview_id":string | null;"p_rating":number | null;"p_decision":string | null;"p_reason_code"?:string | null;"p_comments"?:string | null;"p_visible_to_student"?:boolean | null};Returns:string};
"submit_mock_scorecard":{Args:{"p_mock_id":string | null;"p_communication":number | null;"p_technical":number | null;"p_domain":number | null;"p_overall":number | null;"p_strengths":string | null;"p_improvement_areas":string | null;"p_evaluator_notes":string | null;"p_student_visible_notes":string | null;"p_recommendation":string | null;"p_scoring_version":string | null};Returns:string};
"transition_placement":{Args:{"p_placement_id":string | null;"p_new_status":string | null;"p_reason"?:string | null;"p_effective_at"?:string | null};Returns:undefined};
"withdraw_offer":{Args:{"p_offer_id":string | null;"p_reason":string | null};Returns:undefined}};Enums:Record<string,never>;CompositeTypes:Record<string,never>}};
